In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2778, 9896, 1102, 3859],
 [2778, 9896, 1102, 4444],
 [2778, 7844, 1102, 5018],
 [4966, 3912, 1234, 5751, 2431],
 [4966, 3912, 1234, 5751, 2541],
 [7343, 2778, 4919, 1102, 4469],
 [1123, 7903, 8429, 5751]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2778 9896 1102 3859]
 [   0    0    0    0 2778 9896 1102 4444]
 [   0    0    0    0 2778 7844 1102 5018]
 [   0    0    0 4966 3912 1234 5751 2431]
 [   0    0    0 4966 3912 1234 5751 2541]
 [   0    0    0 7343 2778 4919 1102 4469]
 [   0    0    0    0 1123 7903 8429 5751]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\GEN AI\DL NLP\RNN\simple_rnn_imdb\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 251ms/step


array([[[-1.68349855e-02,  4.89827730e-02,  4.10599746e-02,
          4.56511118e-02,  2.94721760e-02,  3.74559648e-02,
         -4.76812720e-02, -3.68287452e-02, -2.46987697e-02,
         -1.68053135e-02],
        [-1.68349855e-02,  4.89827730e-02,  4.10599746e-02,
          4.56511118e-02,  2.94721760e-02,  3.74559648e-02,
         -4.76812720e-02, -3.68287452e-02, -2.46987697e-02,
         -1.68053135e-02],
        [-1.68349855e-02,  4.89827730e-02,  4.10599746e-02,
          4.56511118e-02,  2.94721760e-02,  3.74559648e-02,
         -4.76812720e-02, -3.68287452e-02, -2.46987697e-02,
         -1.68053135e-02],
        [-1.68349855e-02,  4.89827730e-02,  4.10599746e-02,
          4.56511118e-02,  2.94721760e-02,  3.74559648e-02,
         -4.76812720e-02, -3.68287452e-02, -2.46987697e-02,
         -1.68053135e-02],
        [-7.73901865e-03,  1.46358497e-02,  1.26897804e-02,
          1.31066181e-02,  7.76336342e-03,  2.15177871e-02,
          4.12631035e-03,  1.86678506e-02, -1.907825

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 2778, 9896, 1102, 3859], dtype=int32)

In [18]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>